# Maintenance Windows Configuration
# All times are in UTC
#
# Optional Settings:
# - dc_util_timeout: Timeout for decommission operations in seconds (default: 720)
# - min_availability: Required cluster availability during decommission
#   * PRIMARIES: Keep primary shards available (default)
#   * FULL: Keep all shards available (safest)
#   * NONE: Allow all shards to be unavailable (fastest)

[aqua-darth-vader]
timezone = "UTC"
min_window_duration = 30  # Minimum minutes needed for maintenance
dc_util_timeout = 333     # Timeout for dc_util in seconds (optional, defaults to 720)
min_availability = "NONE" # PRIMARIES, NONE, or FULL (optional, defaults to PRIMARIES)

[[aqua-darth-vader.windows]]
time = "01:00-24:00"
weekdays = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
description = "Evening maintenance window"

[[aqua-darth-vader.windows]]
time = "17:00-21:00"
ordinal_days = ["2nd tue", "3rd mon"]
description = "Monthly maintenance slots"

[tgw-x]
timezone = "UTC"
min_window_duration = 30
dc_util_timeout = 900     # Custom timeout for this cluster
min_availability = "FULL" # Require full availability

[[tgw-x.windows]]
time = "18:00-19:30"
weekdays = ["mon", "tue"]
description = "Short evening window"

[[tgw-x.windows]]
time = "20:00-22:00"
weekdays = ["thu", "fri"]
description = "Late evening window"

[production-cluster]
timezone = "UTC"
min_window_duration = 60
dc_util_timeout = 1200         # Longer timeout for production
min_availability = "PRIMARIES"

[[production-cluster.windows]]
time = "02:00-04:00"
weekdays = ["sat", "sun"]
description = "Weekend early morning maintenance"

[[production-cluster.windows]]
time = "23:00-01:00"
ordinal_days = ["last fri"]
description = "End of month maintenance"

[development-cluster]
timezone = "UTC"
min_window_duration = 15
dc_util_timeout = 600     # Shorter timeout for dev
min_availability = "NONE" # Less strict for development

[[development-cluster.windows]]
time = "12:00-13:00"
weekdays = ["mon", "tue", "wed", "thu", "fri"]
description = "Lunch break maintenance"

[[development-cluster.windows]]
time = "09:00-10:00"
ordinal_days = ["1st mon"]
description = "First Monday of month"

[staging-cluster]
timezone = "UTC"
min_window_duration = 45
dc_util_timeout = 900          # Moderate timeout for staging
min_availability = "PRIMARIES" # Standard availability for staging

[[staging-cluster.windows]]
time = "01:00-03:00"
weekdays = ["wed"]
description = "Mid-week early morning"

[[staging-cluster.windows]]
time = "22:00-23:30"
ordinal_days = ["2nd thu", "4th thu"]
description = "Bi-weekly Thursday evening"


[lime-wicket-systri-warrick]
timezone = "UTC"
min_windows_duration = 15

[[lime-wicket-systri-warrick.windows]]
time = "23:00-23:55"
weekdays = ["mon", "tue", "wed", "thu", "fri"]
description = "Weekly maintenance window"
